/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This column marks the individual sections.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[^'[]*?:/\][^[]*?:/\]*[^'[]*?:/\]$".
 */
export type ColumnNameForTheSectionMarkers = string;
export type ValueRef = string;

/**
 * Maps invoice data to the cells in a spreadsheet.
 */
export interface Mapping {
	meta: MappingMetaInformation;
	'ubl:Invoice': {
		'cbc:CustomizationID': ValueRef;
		'cbc:ProfileID': ValueRef;
		'cbc:ID': ValueRef;
		'cbc:IssueDate': ValueRef;
		'cbc:DueDate'?: ValueRef;
		'cbc:InvoiceTypeCode': ValueRef;
		'cbc:Note'?: ValueRef;
		'cbc:TaxPointDate'?: ValueRef;
		'cbc:DocumentCurrencyCode': ValueRef;
		'cbc:TaxCurrencyCode'?: ValueRef;
		'cbc:AccountingCost'?: ValueRef;
		'cbc:BuyerReference'?: ValueRef;
		'cac:InvoicePeriod'?: DELIVERYORINVOICEPERIOD;
		'cac:OrderReference'?: ORDERANDSALESORDERREFERENCE;
		'cac:BillingReference'?: {
			'cac:InvoiceDocumentReference'?: INVOICEDOCUMENTREFERENCE;
			[k: string]: unknown;
		};
		'cac:DespatchDocumentReference'?: DESPATCHADVICEREFERENCE;
		'cac:ReceiptDocumentReference'?: RECEIPTADVICEREFERENCE;
		'cac:OriginatorDocumentReference'?: TENDERORLOTREFERENCE;
		'cac:ContractDocumentReference'?: CONTRACTREFERENCE;
		'cac:AdditionalDocumentReference'?: {
			'cbc:ID'?: ValueRef;
			'cbc:ID@schemeID'?: ValueRef;
			'cbc:DocumentTypeCode'?: ValueRef;
			'cbc:DocumentDescription'?: ValueRef;
			'cac:Attachment'?: ATTACHMENT;
			[k: string]: unknown;
		};
		'cac:ProjectReference'?: PROJECTREFERENCE;
		'cac:AccountingSupplierParty': SELLER;
		'cac:AccountingCustomerParty': BUYER;
		'cac:PayeeParty'?: PAYEE;
		'cac:TaxRepresentativeParty'?: SELLERTAXREPRESENTATIVEPARTY;
		'cac:Delivery'?: DELIVERYINFORMATION;
		'cac:PaymentMeans'?: {
			'cbc:PaymentMeansCode'?: ValueRef;
			'cbc:PaymentMeansCode@name'?: ValueRef;
			'cbc:PaymentID'?: ValueRef;
			'cac:CardAccount'?: PAYMENTCARDINFORMATION;
			'cac:PayeeFinancialAccount'?: CREDITTRANSFER;
			'cac:PaymentMandate'?: DIRECTDEBIT;
			[k: string]: unknown;
		};
		'cac:PaymentTerms'?: PAYMENTTERMS;
		'cac:AllowanceCharge'?: {
			'cbc:ChargeIndicator'?: ValueRef;
			'cbc:AllowanceChargeReasonCode'?: ValueRef;
			'cbc:AllowanceChargeReason'?: ValueRef;
			'cbc:MultiplierFactorNumeric'?: ValueRef;
			'cbc:Amount'?: ValueRef;
			'cbc:Amount@currencyID'?: ValueRef;
			'cbc:BaseAmount'?: ValueRef;
			'cbc:BaseAmount@currencyID'?: ValueRef;
			'cac:TaxCategory'?: TAXCATEGORY;
			[k: string]: unknown;
		};
		'cac:TaxTotal': {
			'cbc:TaxAmount'?: ValueRef;
			'cbc:TaxAmount@currencyID'?: ValueRef;
			'cac:TaxSubtotal'?: {
				'cbc:TaxableAmount'?: ValueRef;
				'cbc:TaxableAmount@currencyID'?: ValueRef;
				'cbc:TaxAmount'?: ValueRef;
				'cbc:TaxAmount@currencyID'?: ValueRef;
				'cac:TaxCategory'?: VATCATEGORY;
				[k: string]: unknown;
			};
			[k: string]: unknown;
		};
		'cac:LegalMonetaryTotal': DOCUMENTTOTALS;
		'cac:InvoiceLine': {
			'cbc:ID'?: ValueRef;
			'cbc:Note'?: ValueRef;
			'cbc:InvoicedQuantity'?: ValueRef;
			'cbc:InvoicedQuantity@unitCode'?: ValueRef;
			'cbc:LineExtensionAmount'?: ValueRef;
			'cbc:LineExtensionAmount@currencyID'?: ValueRef;
			'cbc:AccountingCost'?: ValueRef;
			'cac:InvoicePeriod'?: INVOICELINEPERIOD;
			'cac:OrderLineReference'?: ORDERLINEREFERENCE;
			'cac:DocumentReference'?: LINEOBJECTIDENTIFIER;
			'cac:AllowanceCharge'?: {
				'cbc:ChargeIndicator'?: ValueRef;
				'cbc:AllowanceChargeReasonCode'?: ValueRef;
				'cbc:AllowanceChargeReason'?: ValueRef;
				'cbc:MultiplierFactorNumeric'?: ValueRef;
				'cbc:Amount'?: ValueRef;
				'cbc:Amount@currencyID'?: ValueRef;
				'cbc:BaseAmount'?: ValueRef;
				'cbc:BaseAmount@currencyID'?: ValueRef;
				[k: string]: unknown;
			};
			'cac:Item'?: ITEMINFORMATION;
			'cac:Price'?: PRICEDETAILS;
			[k: string]: unknown;
		};
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
/**
 * Auxiliary information for the mapping data.
 */
export interface MappingMetaInformation {
	sectionColumn: {
		[k: string]: ColumnNameForTheSectionMarkers;
	};
}
/**
 * A group of business terms providing information on the invoice period. Also called delivery period.
 *                 If the group is used, the invoiceing period start date and/or end date must be used.
 */
export interface DELIVERYORINVOICEPERIOD {
	'cbc:StartDate'?: ValueRef;
	'cbc:EndDate'?: ValueRef;
	'cbc:DescriptionCode'?: ValueRef;
	[k: string]: unknown;
}
export interface ORDERANDSALESORDERREFERENCE {
	'cbc:ID': ValueRef;
	'cbc:SalesOrderID'?: ValueRef;
	[k: string]: unknown;
}
export interface INVOICEDOCUMENTREFERENCE {
	'cbc:ID': ValueRef;
	'cbc:IssueDate'?: ValueRef;
	[k: string]: unknown;
}
export interface DESPATCHADVICEREFERENCE {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface RECEIPTADVICEREFERENCE {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface TENDERORLOTREFERENCE {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface CONTRACTREFERENCE {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface ATTACHMENT {
	'cbc:EmbeddedDocumentBinaryObject'?: ValueRef;
	'cbc:EmbeddedDocumentBinaryObject@mimeCode'?: ValueRef;
	'cbc:EmbeddedDocumentBinaryObject@filename'?: ValueRef;
	'cac:ExternalReference'?: EXTERNALREFERENCE;
	[k: string]: unknown;
}
export interface EXTERNALREFERENCE {
	'cbc:URI': ValueRef;
	[k: string]: unknown;
}
export interface PROJECTREFERENCE {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the Seller.
 */
export interface SELLER {
	'cac:Party': PARTY;
	[k: string]: unknown;
}
export interface PARTY {
	'cbc:EndpointID': ValueRef;
	'cbc:EndpointID@schemeID'?: ValueRef;
	'cac:PartyIdentification'?: {
		'cbc:ID'?: ValueRef;
		'cbc:ID@schemeID'?: ValueRef;
		[k: string]: unknown;
	};
	'cac:PartyName'?: PARTYNAME;
	'cac:PostalAddress': SELLERPOSTALADDRESS;
	'cac:PartyTaxScheme'?: {
		'cbc:CompanyID'?: ValueRef;
		'cac:TaxScheme'?: TAXSCHEME;
		[k: string]: unknown;
	};
	'cac:PartyLegalEntity': PARTYLEGALENTITY;
	'cac:Contact'?: SELLERCONTACT;
	[k: string]: unknown;
}
export interface PARTYNAME {
	'cbc:Name': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the address of the Seller.
 *                     Sufficient components of the address are to be filled to comply with legal requirements.
 */
export interface SELLERPOSTALADDRESS {
	'cbc:StreetName'?: ValueRef;
	'cbc:AdditionalStreetName'?: ValueRef;
	'cbc:CityName'?: ValueRef;
	'cbc:PostalZone'?: ValueRef;
	'cbc:CountrySubentity'?: ValueRef;
	'cac:AddressLine'?: ADDRESSLINE;
	'cac:Country': COUNTRY;
	[k: string]: unknown;
}
export interface ADDRESSLINE {
	'cbc:Line': ValueRef;
	[k: string]: unknown;
}
export interface COUNTRY {
	'cbc:IdentificationCode': ValueRef;
	[k: string]: unknown;
}
export interface TAXSCHEME {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface PARTYLEGALENTITY {
	'cbc:RegistrationName': ValueRef;
	'cbc:CompanyID'?: ValueRef;
	'cbc:CompanyID@schemeID'?: ValueRef;
	'cbc:CompanyLegalForm'?: ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing contact information about the Seller.
 */
export interface SELLERCONTACT {
	'cbc:Name'?: ValueRef;
	'cbc:Telephone'?: ValueRef;
	'cbc:ElectronicMail'?: ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the Buyer.
 */
export interface BUYER {
	'cac:Party': PARTY1;
	[k: string]: unknown;
}
export interface PARTY1 {
	'cbc:EndpointID': ValueRef;
	'cbc:EndpointID@schemeID'?: ValueRef;
	'cac:PartyIdentification'?: PARTYIDENTIFICATION;
	'cac:PartyName'?: PARTYNAME1;
	'cac:PostalAddress': BUYERPOSTALADDRESS;
	'cac:PartyTaxScheme'?: PARTYVATIDENTIFIER;
	'cac:PartyLegalEntity': PARTYLEGALENTITY1;
	'cac:Contact'?: BUYERCONTACT;
	[k: string]: unknown;
}
export interface PARTYIDENTIFICATION {
	'cbc:ID': ValueRef;
	'cbc:ID@schemeID'?: ValueRef;
	[k: string]: unknown;
}
export interface PARTYNAME1 {
	'cbc:Name': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the postal address for the Buyer.
 *                     Sufficient components of the address are to be filled to comply with legal requirements.
 */
export interface BUYERPOSTALADDRESS {
	'cbc:StreetName'?: ValueRef;
	'cbc:AdditionalStreetName'?: ValueRef;
	'cbc:CityName'?: ValueRef;
	'cbc:PostalZone'?: ValueRef;
	'cbc:CountrySubentity'?: ValueRef;
	'cac:AddressLine'?: ADDRESSLINE1;
	'cac:Country': COUNTRY1;
	[k: string]: unknown;
}
export interface ADDRESSLINE1 {
	'cbc:Line': ValueRef;
	[k: string]: unknown;
}
export interface COUNTRY1 {
	'cbc:IdentificationCode': ValueRef;
	[k: string]: unknown;
}
export interface PARTYVATIDENTIFIER {
	'cbc:CompanyID': ValueRef;
	'cac:TaxScheme': TAXSCHEME1;
	[k: string]: unknown;
}
export interface TAXSCHEME1 {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface PARTYLEGALENTITY1 {
	'cbc:RegistrationName': ValueRef;
	'cbc:CompanyID'?: ValueRef;
	'cbc:CompanyID@schemeID'?: ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing contact information relevant for the Buyer.
 */
export interface BUYERCONTACT {
	'cbc:Name'?: ValueRef;
	'cbc:Telephone'?: ValueRef;
	'cbc:ElectronicMail'?: ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the Payee, i.e. the role that receives the
 *             payment.  Shall be used when the Payee is different from the Seller.
 */
export interface PAYEE {
	'cac:PartyIdentification'?: PARTYIDENTIFICATION1;
	'cac:PartyName': PARTYNAME2;
	'cac:PartyLegalEntity'?: PARTYLEGALENTITY2;
	[k: string]: unknown;
}
export interface PARTYIDENTIFICATION1 {
	'cbc:ID': ValueRef;
	'cbc:ID@schemeID'?: ValueRef;
	[k: string]: unknown;
}
export interface PARTYNAME2 {
	'cbc:Name': ValueRef;
	[k: string]: unknown;
}
export interface PARTYLEGALENTITY2 {
	'cbc:CompanyID': ValueRef;
	'cbc:CompanyID@schemeID'?: ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the Seller's tax representative.
 */
export interface SELLERTAXREPRESENTATIVEPARTY {
	'cac:PartyName': PARTYNAME3;
	'cac:PostalAddress': SELLERTAXREPRESENTATIVEPOSTALADDRESS;
	'cac:PartyTaxScheme': PARTYVATIDENTIFIER1;
	[k: string]: unknown;
}
export interface PARTYNAME3 {
	'cbc:Name': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the postal address for the tax representative
 *                 party. Sufficient components of the address are to be filled to comply with legal requirements.
 */
export interface SELLERTAXREPRESENTATIVEPOSTALADDRESS {
	'cbc:StreetName'?: ValueRef;
	'cbc:AdditionalStreetName'?: ValueRef;
	'cbc:CityName'?: ValueRef;
	'cbc:PostalZone'?: ValueRef;
	'cbc:CountrySubentity'?: ValueRef;
	'cac:AddressLine'?: ADDRESSLINE2;
	'cac:Country': COUNTRY2;
	[k: string]: unknown;
}
export interface ADDRESSLINE2 {
	'cbc:Line': ValueRef;
	[k: string]: unknown;
}
export interface COUNTRY2 {
	'cbc:IdentificationCode': ValueRef;
	[k: string]: unknown;
}
export interface PARTYVATIDENTIFIER1 {
	'cbc:CompanyID': ValueRef;
	'cac:TaxScheme': TAXSCHEME2;
	[k: string]: unknown;
}
export interface TAXSCHEME2 {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about where and when the goods and services
 *             invoiced are delivered.
 */
export interface DELIVERYINFORMATION {
	'cbc:ActualDeliveryDate'?: ValueRef;
	'cac:DeliveryLocation'?: {
		'cbc:ID'?: ValueRef;
		'cbc:ID@schemeID'?: ValueRef;
		'cac:Address'?: DELIVERTOADDRESS;
		[k: string]: unknown;
	};
	'cac:DeliveryParty'?: DELIVERPARTY;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the address to which goods and services
 *                     invoiced were or are delivered.
 */
export interface DELIVERTOADDRESS {
	'cbc:StreetName'?: ValueRef;
	'cbc:AdditionalStreetName'?: ValueRef;
	'cbc:CityName'?: ValueRef;
	'cbc:PostalZone'?: ValueRef;
	'cbc:CountrySubentity'?: ValueRef;
	'cac:AddressLine'?: ADDRESSLINE3;
	'cac:Country': COUNTRY3;
	[k: string]: unknown;
}
export interface ADDRESSLINE3 {
	'cbc:Line': ValueRef;
	[k: string]: unknown;
}
export interface COUNTRY3 {
	'cbc:IdentificationCode': ValueRef;
	[k: string]: unknown;
}
export interface DELIVERPARTY {
	'cac:PartyName': PARTYNAME4;
	[k: string]: unknown;
}
export interface PARTYNAME4 {
	'cbc:Name': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about card used for payment contemporaneous with
 *                 invoice issuance.
 */
export interface PAYMENTCARDINFORMATION {
	'cbc:PrimaryAccountNumberID': ValueRef;
	'cbc:NetworkID': ValueRef;
	'cbc:HolderName'?: ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms to specify credit transfer payments.
 */
export interface CREDITTRANSFER {
	'cbc:ID': ValueRef;
	'cbc:Name'?: ValueRef;
	'cac:FinancialInstitutionBranch'?: FINANCIALINSTITUTIONBRANCH;
	[k: string]: unknown;
}
export interface FINANCIALINSTITUTIONBRANCH {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms to specify a direct debit.
 */
export interface DIRECTDEBIT {
	'cbc:ID'?: ValueRef;
	'cac:PayerFinancialAccount'?: PAYERFINANCIALACCOUNT;
	[k: string]: unknown;
}
export interface PAYERFINANCIALACCOUNT {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface PAYMENTTERMS {
	'cbc:Note': ValueRef;
	[k: string]: unknown;
}
export interface TAXCATEGORY {
	'cbc:ID': ValueRef;
	'cbc:Percent'?: ValueRef;
	'cac:TaxScheme': TAXSCHEME3;
	[k: string]: unknown;
}
export interface TAXSCHEME3 {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface VATCATEGORY {
	'cbc:ID': ValueRef;
	'cbc:Percent'?: ValueRef;
	'cbc:TaxExemptionReasonCode'?: ValueRef;
	'cbc:TaxExemptionReason'?: ValueRef;
	'cac:TaxScheme': TAXSCHEME4;
	[k: string]: unknown;
}
export interface TAXSCHEME4 {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing the monetary totals for the Invoice.
 */
export interface DOCUMENTTOTALS {
	'cbc:LineExtensionAmount': ValueRef;
	'cbc:LineExtensionAmount@currencyID'?: ValueRef;
	'cbc:TaxExclusiveAmount': ValueRef;
	'cbc:TaxExclusiveAmount@currencyID'?: ValueRef;
	'cbc:TaxInclusiveAmount': ValueRef;
	'cbc:TaxInclusiveAmount@currencyID'?: ValueRef;
	'cbc:AllowanceTotalAmount'?: ValueRef;
	'cbc:AllowanceTotalAmount@currencyID'?: ValueRef;
	'cbc:ChargeTotalAmount'?: ValueRef;
	'cbc:ChargeTotalAmount@currencyID'?: ValueRef;
	'cbc:PrepaidAmount'?: ValueRef;
	'cbc:PrepaidAmount@currencyID'?: ValueRef;
	'cbc:PayableRoundingAmount'?: ValueRef;
	'cbc:PayableRoundingAmount@currencyID'?: ValueRef;
	'cbc:PayableAmount': ValueRef;
	'cbc:PayableAmount@currencyID'?: ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the period relevant for the Invoice line.
 */
export interface INVOICELINEPERIOD {
	'cbc:StartDate'?: ValueRef;
	'cbc:EndDate'?: ValueRef;
	[k: string]: unknown;
}
export interface ORDERLINEREFERENCE {
	'cbc:LineID': ValueRef;
	[k: string]: unknown;
}
export interface LINEOBJECTIDENTIFIER {
	'cbc:ID': ValueRef;
	'cbc:ID@schemeID'?: ValueRef;
	'cbc:DocumentTypeCode': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the goods and services invoiced.
 */
export interface ITEMINFORMATION {
	'cbc:Description'?: ValueRef;
	'cbc:Name': ValueRef;
	'cac:BuyersItemIdentification'?: BUYERSITEMIDENTIFICATION;
	'cac:SellersItemIdentification'?: SELLERSITEMIDENTIFICATION;
	'cac:StandardItemIdentification'?: STANDARDITEMIDENTIFICATION;
	'cac:OriginCountry'?: ORIGINCOUNTRY;
	'cac:CommodityClassification'?: {
		'cbc:ItemClassificationCode'?: ValueRef;
		'cbc:ItemClassificationCode@listID'?: ValueRef;
		'cbc:ItemClassificationCode@listVersionID'?: ValueRef;
		[k: string]: unknown;
	};
	'cac:ClassifiedTaxCategory': LINEVATINFORMATION;
	'cac:AdditionalItemProperty'?: {
		'cbc:Name'?: ValueRef;
		'cbc:Value'?: ValueRef;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
export interface BUYERSITEMIDENTIFICATION {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface SELLERSITEMIDENTIFICATION {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
export interface STANDARDITEMIDENTIFICATION {
	'cbc:ID': ValueRef;
	'cbc:ID@schemeID'?: ValueRef;
	[k: string]: unknown;
}
export interface ORIGINCOUNTRY {
	'cbc:IdentificationCode': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the VAT applicable for the goods and services
 *                 invoiced on the Invoice line.
 */
export interface LINEVATINFORMATION {
	'cbc:ID': ValueRef;
	'cbc:Percent'?: ValueRef;
	'cac:TaxScheme': TAXSCHEME5;
	[k: string]: unknown;
}
export interface TAXSCHEME5 {
	'cbc:ID': ValueRef;
	[k: string]: unknown;
}
/**
 * A group of business terms providing information about the price applied for the goods and services
 *             invoiced on the Invoice line.
 */
export interface PRICEDETAILS {
	'cbc:PriceAmount': ValueRef;
	'cbc:PriceAmount@currencyID'?: ValueRef;
	'cbc:BaseQuantity'?: ValueRef;
	'cbc:BaseQuantity@unitCode'?: ValueRef;
	'cac:AllowanceCharge'?: ALLOWANCE;
	[k: string]: unknown;
}
export interface ALLOWANCE {
	'cbc:ChargeIndicator': ValueRef;
	'cbc:Amount': ValueRef;
	'cbc:Amount@currencyID'?: ValueRef;
	'cbc:BaseAmount'?: ValueRef;
	'cbc:BaseAmount@currencyID'?: ValueRef;
	[k: string]: unknown;
}
